### ISSUE TITLE
False Positive - Trojan:Win32/Wacatac.B!ml

### ISSUE THREAD

**Issue by SaturnRingssss** [Nenotriple/R-ESRGAN-AnimeVideo-UI#10]
I thought we were good to go but now Windows Defender flagged this as a severe risk relating to the exe file.  So obviously
as a precaution, I have removed it from my PC

![Virus](https://github.com/Nenotriple/R-ESRGAN-AnimeVideo-UI/assets/153692245/27c9c1e0-6481-4d5a-8393-bfe2cd69bd45)

**Comment by Nenotriple** [comment]
I understand your concern, and I feel terrible because I know how it feels when a program seems "sketchy". This is a common issue when standalone executables are created using PyInstaller. The issue basically boils down to me not digitally signing the application ($$$). There's no solution that I'm aware of.


This is a widely reported issue, as evidenced by numerous discussions and reports on platforms like GitHub and Reddit.

https://github.com/pyinstaller/pyinstaller/issues/5854
https://github.com/pyinstaller/pyinstaller/issues/5492
https://www.reddit.com/r/learnpython/comments/im3jrj/windows_defender_thinks_that_code_i_wrote_using/
https://www.reddit.com/r/learnpython/comments/e99bhe/why_does_pyinstaller_trigger_windows_defender/
https://www.reddit.com/r/learnpython/comments/117216r/exe_compiled_by_pyinstaller_shows_up_as_virus/

As for security, the best assurance I can provide is transparency. The source code for this application is open for anyone to inspect. I assure you that no malicious code has been included.

I wish it was an easy fix, but it's not. I'm sorry.

If you want to use the app, you'll need to create an exclusion in windows defender. It's up to you, always follow your nose. 🧙

**Comment by SaturnRingssss** [comment]
Thanks for the reply, I am going to go ahead and run the program anyway.  I will just set Windows Defender to allow
on device.  The program shows great promise as it did not crash, the UI portion is good.  I have tried other programs
and they just don't perform without having one issue after another. 

Just a quick question, what model should I use for removing artifacts from a video in 1x or 2x

Thanks again, greatly appreciated.

**Comment by SaturnRingssss** [comment]
Thanks for the reply, I am going to go ahead and run the program anyway. I will just set Windows Defender to allow
on device. The program shows great promise as it did not crash, the UI portion is good. I have tried other programs
and they just don't perform without having one issue after another.

Just a quick question, what model should I use for removing artifacts from a video in 1x or 2x

Thanks again, greatly appreciated.
Mike

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by Nenotriple** [comment]
Thank you so much for the kind words, it really means a lot. I'm just making a thing I want, you know? So it's super cool to see others have any interest in it.

The thing about scaling factor is kinda a misnomer. All scaling options x1, x2, x3, x4 actually scale the image up 4x then scale the image back down to fit the desired scaling factor. This is a limitation of Real-ESRGAN portable.

If you take a look at the [animated comparisons,](https://github.com/Nenotriple/R-ESRGAN-AnimeVideo-UI/wiki/%E2%9A%96%EF%B8%8F-Comparisons#animated-comparisons) you can see from the first image that x1 scaling is kinda broken and doesn't produce smooth pixels. The option is there for convenience really.

If you want to output a video the same size as the input, then I suggest using the resize frames option. You can do this two ways.

1) Enable auto mode, then go to the Video > Extra settings > Enable: Auto resize upscaled frames before merging. 
    - Lets say you have a 1280x720 video. You selected upscale x2. Just enable the auto resize option and it will scale the upscaled frames down to half size (50%), or from 2560x1440 to 1280x720. You could enter a percentage to scale, or an exact resolution.

2) You can resize frames without auto enabled by first extracting/upscaling, then go to the "Tools" menu and select "Resize: ..."
    - It works the same as before, it's just not tied to the auto mode.

I could make it so x1 scaling actually uses my method of scaling frames, it would be a little slower, but much better looking.

-----

As far as what model to use, it depends on the content of the video, and how long you're willing to wait.

`realesr-animevideov3` Is my top choice for cartoon/anime/manga/etc., and it can work ok with real life video, but it's not fantastic. It's super fast, and generally creates clean results.

`RealESRGAN_General_x4_v3` Is another fast model that does work good, but it can seriously smooth out detail.

Both `realesrgan-x4plus` and `realesrgan-x4plus-anime` probably could produce better results than the above, but the output is so slow I rarely use them. It would be ok for very small video.

-----

Sorry to ramble, if you have any other questions or concerns just let me know.
