### ISSUE TITLE
App window height exceeds desktop height

### ISSUE THREAD

**Issue by the-liquid-metal** [Nenotriple/R-ESRGAN-AnimeVideo-UI#17]
My desktop is 1920x1080.

![image](https://github.com/Nenotriple/R-ESRGAN-AnimeVideo-UI/assets/238188/7d83c863-ffd6-46ef-a9c1-0ffd3821b3c9)

**Comment by Nenotriple** [comment]
I'm guessing your desktop scaling options are greater than 100%, because the app window height is set to 715px, so it should fit just fine.

You can check your scaling settings by going to Windows Settings and searching for “Make everything bigger”. If your scaling is set to more than 100%, try setting it down to 100%. This should make the window fully visible on your desktop.

Thank you for bringing this to my attention, but I don’t have the time to work on this issue at the moment. I hope this suggestion helps you.

**Comment by the-liquid-metal** [comment]
> I'm guessing your desktop scaling options are greater than 100%, because the app window height is set to 715px, so it should fit just fine.
> 
Yes it is (150%). Without it, i am struggling to read my screen. Moreover, with this zoom level, your app looks normal to me. Is there any way to fix this?

**Comment by Nenotriple** [comment]
Unfortunately, the app is coded not to be resizable because it's much easier/faster to develop the interface. If you were to resize the window height, it would just squish the buttons out of view, and that wouldn't fix anything.

The only thing I can really do is restructure the UI so it's wide instead of tall, but that's not an entirely simple or quick process. Sorry, but I don't have any real solution that would "solve" this for you.

<br>

You might find the Windows magnifier useful when using the app at 100% scale. You can enable it with the `Windows logo key` and `Plus sign` (+).

Or maybe you can just use the app normally at 150% scale? It doesn't look like any controls are cutoff.

**Comment by the-liquid-metal** [comment]
> 
> Or maybe you can just use the app normally at 150% scale? It doesn't look like any controls are cutoff.
>
This is not always true. Somehow, the app displays the lowest button. But most of the time these buttons are not visible.

![image](https://github.com/Nenotriple/R-ESRGAN-AnimeVideo-UI/assets/238188/7bf4f982-c5c7-449b-8ad3-b7af0efb29aa)

> but that's not an entirely simple or quick process. Sorry, but I don't have any real solution that would "solve" this for you.
> 
How about merging "single image upscale" and "batch upscale"? Many Real-ESRGAN GUI applications I've found are designed like this.

**Comment by the-liquid-metal** [comment]
![image](https://github.com/Nenotriple/R-ESRGAN-AnimeVideo-UI/assets/238188/2aaeaa88-75e5-4c55-9d33-f561746827c0)
IMHO, The jumbo "Auto Rezise frames" text is less important, and can be removed so that the lowest text can be displayed entirely. Its tooltip can be merged with both controls below,

**Comment by the-liquid-metal** [comment]
> How about merging "single image upscale" and "batch upscale"? Many Real-ESRGAN GUI applications I've found are designed like this.

Even further, all four functionalities can be combined:
- a single select control with items: "upscale image(s)" and "resize image(s)".
- input control, which can be single image (file) or batch (folder)
- output control, which can be single image (file) or batch (folder)
- model and factor controls (previously on the top of the tab), which is enabled if  "upscale image(s)" is selected.
- resolution control, which is enabled if  "resize image(s)" is selected.
- a single run button.

This will save a lot of space and more intuitive.

**Comment by Nenotriple** [comment]
I really appreciate your ideas. Eventually, I would like to make the interface cleaner and more intuitive.

I've looked at it some more, and I think the easiest compromise is to remove the info text at the top of the UI. Almost everything is printed on the console anyway, so there isn't much lost. It reduces the window height from 715px, to 490px. This should come out to something like 735px at 150% scale. 

You can download v1.18.b from [here.](https://github.com/Nenotriple/R-ESRGAN-AnimeVideo-UI/releases/tag/v1.18.b)

You can use this release by dropping the v1.18.b executable in the same folder as the v1.18 executable.

This should make the window much shorter:

![Untitled3](https://github.com/Nenotriple/R-ESRGAN-AnimeVideo-UI/assets/70049990/c3c6be55-f7fe-4b65-a5a2-8dd4a740a24d)

![Untitled](https://github.com/Nenotriple/R-ESRGAN-AnimeVideo-UI/assets/70049990/f53091e8-3915-4baa-87ed-c073f8e23d5e)

![Untitled2](https://github.com/Nenotriple/R-ESRGAN-AnimeVideo-UI/assets/70049990/77cd804d-fe8d-46f1-84fa-097489022230)

v1.18.b note: I just commented out the "pack" function call for the label frame. This means that all the widgets are still being created and updated, but not displayed. Then I reduced the window height to 490px.

**Comment by the-liquid-metal** [comment]
Thanks for the quick solution. That's all I need at the moment, as I use this app only for evaluation purposes, not as an everyday tool (yet).

Please consider my design proposal if you have plans to refactor this app.

One more suggestion: replace the console window with a dedicated "log" tab, alongside the "video" and "images" tabs.
