### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by luctiger** [Nenotriple/R-ESRGAN-AnimeVideo-UI#3]
Hi, thank you for this! I have been attempting to use this code but have been running into issues, and was hoping to get help here.

Every time I attempt to select a video, I am met with the following error (note that I printed "result" to examine its contents):
![Capture](https://github.com/Nenotriple/R-ESRGAN-AnimeVideo-UI/assets/46543234/d0f30f79-cfd3-4aac-ac95-d36bd9ca5152)

The cause looks to be because the subprocess.run() on line 401 is returning with returncode=1, citing "no such file or directory." However, I do not really have any idea how to resolve something like this, what I might be doing wrong, etc.

Any help would be greatly appreciated, thank you!

**Comment by Nenotriple** [comment]
This is a tricky one. It's strange how it's reporting an error "No such file..." Then it goes on to report an error with framerate collection. It's possible it's a simple issue like file permissions not letting the script access the file, but I'm really not sure.

When I look more into the framerate issue, it looks like it could be because of the way I'm handling the value as an integer.
I've altered the select_video function to now handle the framerate in either float or integer.

I'd like you to try out this v1.11 "beta" that may fix the issue. You should be able to simply overwrite the old script.

[R-ESRGAN-AnimeVideo-UI.zip](https://github.com/Nenotriple/R-ESRGAN-AnimeVideo-UI/files/13116071/R-ESRGAN-AnimeVideo-UI.zip)

If this doesn't work, I could handle the ValueError by letting the user manually enter a framerate.

**Comment by luctiger** [comment]
It worked!!

**Comment by Nenotriple** [comment]
I'm really glad to hear that! 👍 

I've been looking into it today, and I realized this is actually an old issue that's been preventing info collection when it shouldn't be an issue. So it's great to squash this.

I should have a proper v1.11 ready later today with several more fixes and some qol changes. The script should now be much more robust when handling framerate and media info collection for various scenarios.

Don't hesitate to drop in with any suggestions or more bug reports!
